import re
import os
from flask import Flask, jsonify, request, redirect

app = Flask(__name__)

# The name of your existing M3U file generated by your other script
M3U_FILE_PATH = "playlist.m3u"

# In-memory storage for our parsed M3U data
STREAMS = {}
CATEGORIES = {}

def load_m3u_file():
    """
    Reads your existing M3U file and parses it into Xtream-compatible data.
    """
    global STREAMS, CATEGORIES
    STREAMS.clear()
    CATEGORIES.clear()
    
    if not os.path.exists(M3U_FILE_PATH):
        print(f"[!] Warning: {M3U_FILE_PATH} not found. Please place it in the same directory.")
        return

    cat_id_counter = 1
    stream_id_counter = 1
    
    with open(M3U_FILE_PATH, "r", encoding="utf-8") as f:
        lines = f.readlines()

    current_metadata = {}
    
    for line in lines:
        line = line.strip()
        
        # Parse the Metadata line (#EXTINF)
        if line.startswith("#EXTINF"):
            # Extract Logo
            logo_match = re.search(r'tvg-logo="(.*?)"', line)
            logo = logo_match.group(1) if logo_match else ""
            
            # Extract Category (group-title)
            group_match = re.search(r'group-title="(.*?)"', line)
            cat_name = group_match.group(1) if group_match else "Uncategorized"
            
            # Extract Movie Name (everything after the last comma)
            name = line.split(',')[-1].strip()
            
            # Assign a Category ID
            if cat_name not in CATEGORIES.values():
                CATEGORIES[str(cat_id_counter)] = cat_name
                cat_id = str(cat_id_counter)
                cat_id_counter += 1
            else:
                cat_id = [k for k, v in CATEGORIES.items() if v == cat_name][0]
                
            current_metadata = {
                "name": name,
                "stream_icon": logo,
                "category_id": cat_id,
                "stream_id": str(stream_id_counter)
            }
            stream_id_counter += 1
            
        # Parse the URL line (pointing to your Scraper Server)
        elif line and not line.startswith("#"):
            if current_metadata:
                current_metadata["target_url"] = line
                # Save to our master dictionary using stream_id as the key
                STREAMS[current_metadata["stream_id"]] = current_metadata
                current_metadata = {}

    print(f"[+] Loaded {len(STREAMS)} movies and {len(CATEGORIES)} categories from {M3U_FILE_PATH}")


@app.route('/player_api.php', methods=['GET', 'POST'])
def xtream_api():
    """The Mock Xtream Server Endpoint for menus and API logins."""
    action = request.args.get('action')
    username = request.args.get('username')

    # 1. Login Authorization
    if not action:
        return jsonify({
            "user_info": {
                "auth": 1,
                "status": "Active",
                "username": username,
                "exp_date": "null",
                "is_trial": "0"
            },
            "server_info": {
                "url": request.host.split(':')[0],
                "port": request.host.split(':')[1] if ':' in request.host else "80",
                "server_protocol": "http"
            }
        })

    # 2. Return Categories (VOD)
    if action == "get_vod_categories":
        cat_list = []
        for cat_id, cat_name in CATEGORIES.items():
            cat_list.append({
                "category_id": cat_id,
                "category_name": cat_name,
                "parent_id": 0
            })
        return jsonify(cat_list)

    # 3. Return the Movie List (VOD)
    if action == "get_vod_streams":
        stream_list = []
        for idx, (stream_id, data) in enumerate(STREAMS.items()):
            stream_list.append({
                "num": idx + 1,
                "name": data["name"],
                "stream_type": "movie",
                "stream_id": stream_id,
                "stream_icon": data["stream_icon"],
                "category_id": data["category_id"],
                "container_extension": "m3u8"
            })
        return jsonify(stream_list)

    return jsonify({})


@app.route('/get.php', methods=['GET', 'POST'])
def get_m3u_playlist():
    """
    Fallback for IPTV apps (like Smarters/VLC) that request the full playlist 
    via get.php instead of using the JSON API. (e.g., type=m3u_plus)
    """
    username = request.args.get('username', 'admin')
    password = request.args.get('password', 'admin')
    
    # Rebuild an Xtream-formatted M3U file from our loaded memory
    lines = ["#EXTM3U"]
    
    for stream_id, data in STREAMS.items():
        name = data.get("name", "Unknown")
        logo = data.get("stream_icon", "")
        cat_id = data.get("category_id", "")
        category = CATEGORIES.get(cat_id, "Uncategorized")
        
        # Construct the standard Xtream playback URL
        # e.g., http://YOUR_IP:8080/movie/admin/admin/1.m3u8
        base_url = request.host_url.rstrip('/')
        playback_url = f"{base_url}/movie/{username}/{password}/{stream_id}.m3u8"
        
        extinf = f'#EXTINF:-1 tvg-logo="{logo}" group-title="{category}", {name}'
        lines.append(extinf)
        lines.append(playback_url)
        
    m3u_content = "\n".join(lines)
    
    # Return it as a downloadable M3U file format
    return m3u_content, 200, {'Content-Type': 'application/x-mpegurl'}


@app.route('/movie/<username>/<password>/<stream_id>')
def play_movie(username, password, stream_id):
    # This splits "209.m3u8" at the dot, leaving us with just "209"
    clean_id = stream_id.split('.')[0]
    clean_id = re.sub(r'\D', '', clean_id)
    
    if clean_id in STREAMS:
        # It finds your link: http://192.168.1.11:5000/watch/tmdb-1404791
        target_url = STREAMS[clean_id]["target_url"] 
        print(f"[*] App requested {stream_id}. Redirecting to your scraper: {target_url}")
        
        # This sends the IPTV app straight to your Playwright server!
        return redirect(target_url, code=302) 
    else:
        return "Stream not found", 404


# Load the M3U file immediately when the app is imported/started
load_m3u_file()

if __name__ == '__main__':
    # This is only used for local development running: python app.py
    app.run(host='0.0.0.0', port=8080, debug=True)
